### ISSUE TITLE
Extending mtail with the prometheus client

### ISSUE THREAD

**Issue by groob** [google/mtail#10]
Hi, 

I am trying to monitor an application that makes some metrics available in an XML document and the rest I have to get by parsing logs. mtail looked like a good fit, but I wanted to also take the metrics and from the XML document and add them to /metrics. I thought I'll just write my own main.go and add the extra bits there. Here's where I ran into some trouble:

mtail does not use the official prometheus go client. If I want to add some metrics to /metrics, I can't use `m.Run()` or `m.Serve()`. There's a workaround - `m.StartTailing()` Then I can call m.WriteMetrics() and pip that json into a decoder, then decode it into a metrics struct. 
This works, but it's not very convenient. I'm taking the unexported metrics store from m.Mtail, encoding it into json, then decoding it back into another struct of the same type. 

I'd like to see one of these two changes in mtail if possible:
* rewrite the prometheus exporter to use the official prometheus client. This would be ideal as it would allow mtail to be easily extended with additional metrics that don't come from a log. 
* change the Mtail struct to export Metrics directly without first encoding/decoding from JSON. 

I'd be glad to submit a pull request with a prometheus exporter that uses the official client library if you're not opposed to such a change.

**Comment by jaqx0r** [comment]
I think the best way to solve your problem is not to have mtail read your
logs but have a separate program beside it that converts the XML into
Prometheus metrics. This should be much easier than trying to add the
feature to mtail.

The internal variable store would have to be totally rebuilt to use the
official prom client and mtail is not a prom-only tool, so that will affect
all the other exports too. (I'm not saying it couldn't happen, but I'd like
to see other justification.) The metrics are not encoded in json however,
only exported if you want that format, which is really just a debugging aid.

XML parsing in mtail is not a feature I want to add. I think it is
appropriate to have other tools proxy metrics from other formats (I.e. not
log files) into monitoring systems, many small tools working together
rather than one swiss army knife.

Thanks for the suggestion though and I appreciate you wanting to solve your
problem with mtail, that is flattering!  I'm sorry that I won't accept the
pull request.

However if you were to do it, create the metric from the XML by using the
interface to the metrics.Store object, adding them to the internal storage
will allow them to be exported in all formats including Prometheus without
changing the client code.

**Comment by groob** [comment]
Hi @jaqx0r,

Thank you for your reply. I did not mean to request XML parsing as a feature request for mtail and I understand how that would be outside the scope of this project. 
I just wanted for a way to write additional prometheus data to "/metrics". 

I did look into adding metrics to `mtail.Mtail`, but the metrics.Store object in the struct is private. Did I overlook something?

Here is what I ended up doing in my program: https://github.com/groob/caching_exporter/blob/master/mtail_collector.go#L21
The above solution works fine, except that the only way to access the metrics store in Mtail is by serializing to json first.

**Comment by jaqx0r** [comment]
Are you trying to link in the mtail object as a library to a new program?
That's cool, but I hadn't planned for that :)

I would of course accept a PR to make the useful objects in mtail.Mtail
public, especially the metric store, because all of its members are also
public.  Alternatively I'd accept a PR that moves the initialisation of the
store object to part of the Options struct and have the mtail object hold a
pointer to it instead of a full value, which would mean you could create
your own Store outside of mtail.New and pass it in, then having full access
to the Store with your own reference.

**Comment by jaqx0r** [comment]
I've pushed a change to head that lets you pass in your own metrics.Store
to the options struct; if it's nil, then you get the same behaviour as
before.

https://github.com/google/mtail/blob/master/mtail/mtail.go#L144

Let me know if this helps, it should mean you don't have to do the JSON
serialisation dance.

**Comment by groob** [comment]
Thank you for making the change. I believe this is all that's needed.
