### ISSUE TITLE
Wishlist: logic operators

### ISSUE THREAD

**Issue by TheTincho** [google/mtail#100]
Hi, it's me again :-)

I was trying to simplify some mtail programs, and noticed I can't do things like `($var == "foo" || $var == "var") { ..}`.

I notice there are bitwise operators (which I guess nobody has ever used :)), but if I try to use them, it is not happy either:
```
postfix.mtail:41:4-50: Integer types expected for bitwise op '\ue028', got String and String
```

**Comment by jaqx0r** [comment]
The problem you're seeing here is that strings are not comparable.  But,
they should be: we discussed in #68 that it's going to be easy to fix once
that issue is done.

I reckon you're right about no-one ever using the and/or operators :)
 Let's just make them logical instead of bitwise.  I think they're not even
really bitwise, the error just says so and it's inaccurate.

**Comment by TheTincho** [comment]
Oh, I thought the string comparison was fixed now. It seems to work when using latest HEAD.. I don't know what my programs are doing otherwise :)

For example, it is used extensively in the [postfix example](https://github.com/google/mtail/blob/master/examples/postfix.mtail) I wrote

**Comment by jaqx0r** [comment]
Oh how odd/cool :)

**Comment by jaqx0r** [comment]
I have a change in progress to fix this:

1. add the logical operators to the language [done]
2. unittest the existing string comparison (which does exist, just not exercised by tests)
3. fix nested comparisons (which do not emit correct bytecode due to the way a binary expression and conditional emit is currently implemented)
4. add support for parenthetical expressions once that's done

**Comment by TheTincho** [comment]
Thanks!!

**Comment by jaqx0r** [comment]
2 is done: I misspoke, it was part tested.

3 is done, too.
