### ISSUE TITLE
Mtail fails to build if $GOPATH is a list

### ISSUE THREAD

**Issue by BlessJah** [google/mtail#121]
When a **$GOPATH** is a list goyacc code generation will fail.

The problem is use of **$GOPATH** in following line. It seems that dropping `$GOPATH/bin/` solves the problem.

https://github.com/google/mtail/blob/f579e5ed58f3740dc19359e967191c2327f0e3ea/vm/compiler.go#L5

**Comment by BlessJah** [comment]
Please note that it requires `goyacc` to be in `$PATH`.

**Comment by jaqx0r** [comment]
Ugh.  https://github.com/golang/go/wiki/GOPATH says $GOPATH can be a list, which I assumed not the case.  There's no requirement that $GOPATH/bin is in $PATH which is why this piece of code is there in the first place:
d3c48cc336b790fb021256b8e647c8440a5abb98

I can undo that change if you can convince me that users should have $GOPATH/bin in their $PATH.

**Comment by ncabatoff** [comment]
'go help gopath' says "new packages are always downloaded into the first directory
in the list".  Maybe we could change the makefile to define a $var that holds the first element of $GOPATH, and have the go:generate line use $var/bin instead?  This wouldn't be perfect but better than the current situation I think.

**Comment by jaqx0r** [comment]
That sounds like a good solution, thanks!
