### ISSUE TITLE
Add support for polling as an optional way to tail files (e.g. to read logs from network shares)

### ISSUE THREAD

**Issue by riclib** [google/mtail#157]
As a real case from a customer of mine, I'd like to read logs that are written to a network share. This would require having some (optional) polling mechanism, as fsnotify doesn't work for network shares.

I'm ready to put in the work to implement it, what do you think of adding this feature @jaqx0r @jnovack ?

**Comment by jaqx0r** [comment]
I think it'd be tricky to add without having the user to specify that they'd be polled logs instead of fsnotify logs.  But... if fsnotify can provide a useful error when you try to add the logs to the watcher (e.g. in watcher/log_watcher.go's Add method) then you could add them to a list of files that get polled every interval with a simple goroutine loop.

You'd need to set up a shutdown channel similarly to how tailer/tail.go handles shutdown in it's Close() method for your polling goroutine.

**Comment by riclib** [comment]
I was thinking of adding it as a --poling option that would apply globally. If you need to poll some and fsnotify some just run two separate mtails, they're probable different logs anyway 😀

**Comment by riclib** [comment]
elegant implementation would be to have an interface for the tailer and have separate classes with a polling and with the fsnotify implementations.

If I come up with an elegant and efficient implementation would you accept the pull request?

**Comment by jaqx0r** [comment]
That seems fair.  Go ahead, but please lots of tests :-)

**Comment by jaqx0r** [comment]
My quick search turned up the probability that inotify add watch on NFS succeeds and then just doesn't return any events.  Handling this automatically in mtail would require some OS-specific cleverness to determine if you're on a remote mount, which sounds complex and fallible.  Let's go with the flag.

**Comment by jnovack** [comment]
fsnotify on network shares has been a bane of any system administrator for years.  it's well known and much despised.

The majority of (log-monitoring) applications accept it and do NOT attempt to work-around it (as that would get message on different OSes multiplied out by different programs doing different things). Mostly we just log ship.  rsyslog or logstash ftw.

But on the OFF chance we need to mount and scrape, if you were attempt it, I believe the `-polling` option would be fair to poll all logs under that instance of mtail.  With plenty of warning in the mtail logs that it's happening and ill-advised.

Logs could grow to the GBs, so if you are at 11:55pm and you have a 2.3GB log file of the day, you may wish to rethink polling it over the network every second for updates.

At a minimum, you want to keep the last filesize so you can `seek()` to the end.  Prior to submitting the PR, I suggest testing this with a 2+GB file over a NFS or SMB mount and confirm polls are just as quick with a 1KB file.

I have no say here, but that's what I'll be testing. ;)

**Comment by riclib** [comment]
so two parameters --polling and --poll_interval 😀 @jnovack 

I'll try to come up with something that is efficient both for log drops and for logs getting written directly to the network share. Will take me a at least couple weeks, don't hold your breath waiting 🤤

**Comment by jaqx0r** [comment]
Frankly I think a better overall solution would be to ship logs over TCP
with, e.g. rsyslog. But if people already have a network share I don't want
to make them spin up more infrastructure on my behalf.

Interval flag is a good idea, thanks.

**Comment by TheTincho** [comment]
I second this. Mtail currently does not work in mips64el due to fsnotify being broken there (not sure where the problem is, there is a bug open there: fsnotify/fsnotify#241). Making that arch always poll instead of use inotify would solve this issue for me.

**Comment by mkrakowitzer** [comment]
I also have this requirement for some legacy IBM AIX hosts. 
* mtail cant be compiled properly on AIX as it lacks support for inotify
* The version of syslog that is supported cannot stream application logs that are not written to the syslog facility. 

Our current hacky solution is to share them over NFS, tail the log files and redirect the output to a local filesystem which mtail then parses. 

A mechanism to have mtail poll the files would be a cleaner solution.

**Comment by jnovack** [comment]
@mkrakowitzer This starts to tangent the conversation, which I do not want to continue.  I'm answering this here because I feel that there will just be many other people with this issue that want to run mtail over NFS and keep running into the same errors.  If you have questions, please contact me outside of this thread.

As stated previously, NFS does not honor inotify, this is a well-known, well-documented issue.  I would not advise working around it.  I've already mentioned issues above, **the current best work-around is log shipping**.

Work within the system to get the logs off the system.  I would recommend a poller native to AIX which sends the logs to syslog (`tail2syslog` comes to mind).  **Then once the files are off in a more modern, capable, and user-friendly environment, feel free to run `mtail` on the shipped logs.**

**Comment by jaqx0r** [comment]
I've gone with the super simple option: a flag, if set, causes all files to be read after each poll interval.

It means the logs on these filesystems have to exist before mtail starts, because it won't see the file creation events.  I'll be interested to know if this causes any problems.

**Comment by andyzasl** [comment]
>It means the logs on these filesystems have to exist before mtail starts, because it won't see the file creation events. I'll be interested to know if this causes any problems.

Why not to do listing at the same time?
