### ISSUE TITLE
Binary does not work

### ISSUE THREAD

**Issue by aminemarref** [google/mtail#181]
Hi,

I have downloaded the program from [1] below, but executing it in Windows 10, gives the message:

`F0927 06:32:15.988112    3396 main.go:109] No mtail program directory specified; please use -progs`

Any ideas?

Thanks.

[1] [https://github.com/google/mtail/releases/download/v3.0.0-rc16/mtail_v3.0.0-rc16_windows_amd64.exe](url)

**Comment by jaqx0r** [comment]
mtail is an interpreter for your own programs.  To start mtail, it needs to
know where to load them, the -progs flag tells it where to load them from.

See the examples in the directory 'examples' for what they look like, or
the github website for the Programming guide.

The Deployment guide also on the website might also help:
https://github.com/google/mtail/blob/master/docs/Deploying.md

Let me know if any of those docs are confusing!  I think because of your
question I can do a better job of explaining how to set up mtail, too.

**Comment by aminemarref** [comment]
Thank you,

My bad, I understood its purpose incorrectly.

A.
