### ISSUE TITLE
JSON parsing

### ISSUE THREAD

**Issue by SuperQ** [google/mtail#183]
We have a number of logs that are converting to JSON format.

It would be useful to have a log reader option for reading in json logs that pre-populate matching group variables.

Is this feasible?

**Comment by SuperQ** [comment]
Yes, it's one json blob per line.

Here's a sample (pretty-formatted)
```json
{
  "time": "2018-10-27T06:30:16.844Z",
  "severity": "INFO",
  "duration": 22.49,
  "db": 4.21,
  "view": 18.279999999999998,
  "status": 401,
  "method": "POST",
  "path": "/api/v4/internal/allowed",
  "params": {
    "action": "git-receive-pack",
    "changes": "X X refs/heads/master\n",
    "gl_repository": "project-X",
    "project": "/var/opt/gitlab/git-data/repositories/X/X.git",
    "protocol": "web",
    "env": "{\"GIT_ALTERNATE_OBJECT_DIRECTORIES\":[],\"GIT_ALTERNATE_OBJECT_DIRECTORIES_RELATIVE\":[],\"GIT_OBJECT_DIRECTORY\":null,\"GIT_OBJECT_DIRECTORY_RELATIVE\":null}",
    "user_id": "X",
    "secret_token": "[FILTERED]"
  },
  "host": "int.gstg.gitlab.net",
  "ip": "X.X.X.X, X.X.X.X",
  "ua": "Ruby",
  "route": "/api/:version/internal/allowed",
  "queue_duration": 10.79,
  "gitaly_calls": 0
}
```

I guess you might be right, handling the nested data structure just doesn't fit with mtail parsing.

**Comment by jaqx0r** [comment]
If it's one blob per line, I reckon you can do it with mtail; any line that
has a ^{.*}$ but you will have to match each key explicitly.

Issue #162 covers a feature request for learning what the key part is in
this; I didn't work on it because I think it would be expensive but reopen
that issue if you feel strongly that it would make your life easier.
