### ISSUE TITLE
Problem parsing Apache logs

### ISSUE THREAD

**Issue by PsychoSid** [google/mtail#185]
Hitting this which is writing massive mtail logs:-

I1026 09:31:01.910781   20051 vm.go:76] apache_metrics.mtail: Runtime error: conversion of "" to int failed: strconv.ParseInt: parsing "": invalid syntax
I1026 09:31:01.910830   20051 vm.go:77] VM stack:
goroutine 12 [running]:
runtime/debug.Stack(0xc0002c3500, 0x28, 0xc00048be18)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/google/mtail/vm.(*VM).errorf(0xc00009d720, 0x86af83, 0x2, 0xc00048be18, 0x1, 0x1)
        /go/src/github.com/google/mtail/vm/vm.go:77 +0x113
github.com/google/mtail/vm.(*VM).execute(0xc00009d720, 0xc000220550, 0x35, 0x7d30a0, 0xc0001f28d8)
        /go/src/github.com/google/mtail/vm/vm.go:328 +0x2bf6
github.com/google/mtail/vm.(*VM).processLine(0xc00009d720, 0xc000421540)
        /go/src/github.com/google/mtail/vm/vm.go:692 +0x140
github.com/google/mtail/vm.(*VM).Run(0xc00009d720, 0x61706163, 0xc000070540, 0xc0000705a0, 0xc000070600)
        /go/src/github.com/google/mtail/vm/vm.go:711 +0xf5
created by github.com/google/mtail/vm.(*MasterControl).CompileAndRun
        /go/src/github.com/google/mtail/vm/mcp.go:241 +0x70d
I1026 09:31:01.910836   20051 vm.go:78] Dumping vm state
I1026 09:31:01.910841   20051 vm.go:79] Name: apache_metrics.mtail
I1026 09:31:01.910846   20051 vm.go:80] Input: &logline.LogLine{Filename:"/var/log/httpd/ssl_access_log", Line:"10.12.18.4 - - [26/Oct/2018:09:31:01 -0700] \"POST /OSPC/cop-payments/cspViolationListener HTTP/1.1\" 200 - conn=+ 104760 373 7353 7 coppayments.example.com TLSv1.2 DHE-RSA-AES256-GCM-SHA384"}
I1026 09:31:01.910870   20051 vm.go:81] Thread:
I1026 09:31:01.910873   20051 vm.go:82]  PC 17
I1026 09:31:01.910877   20051 vm.go:83]  Matched false
I1026 09:31:01.910881   20051 vm.go:84]  Matches map[0:[10.12.18.4 - - [26/Oct/2018:09:31:01 -0700] "POST /OSPC/cop-payments/cspViolationListener HTTP/1.1" 200 - conn=+ 104760 373 7353 7 coppayments.example.com TLSv1.2 DHE-RSA-AES256-GCM-SHA384 10.12.18.4 - - 26/Oct/2018:09:31:01 -0700 - POST /OSPC/cop-payments/cspViolationListener HTTP/1.1 200 -  conn=+ 104760 373 7353 7 coppayments.example.com TLSv1.2 DHE-RSA-AES256-GCM-SHA384]]
I1026 09:31:01.910898   20051 vm.go:85]  Timestamp 2018-10-26 09:31:01 -0700 -0700
I1026 09:31:01.910910   20051 vm.go:86]  Stack []

I am somewhat at a loss to debug this. Any idea on how to :)

Thanks

**Comment by jaqx0r** [comment]
What version of mtail are you using?

The error is on the first line, there is a capture reference that is
currently matching nothing in that line, which you're using in a numeric
context.  This causes the program to abort on this log line input.

The log line input is being printed at vm.go:80, which might help.

If you dump the program bytecode with mtail --dump_bytecode you will see
where the program counter is when the program is terminating, (PC 17)  I
can tell from thr stack trace that vm.go:328 is in the icmp instruction, so
it looks like some case where you're tyring to compare some capture ref
against a number.

The line vm.go:84 tells me what the current capture groups are, and there's
only one entry in the map, the whole string (capture reference 0).  So that
doesn't help indicate what cap ref is being referenced, but with the full
bytecode being dumped that will tell us.

I've been thinking about adding debug symbols in the program so we could
give a better message here and explain what is not able to be converted.

**Comment by PsychoSid** [comment]
Thanks for the reply. The version is v3.0.0-rc16 I have attached a cut down version of the output (as it grows very fast) but hopefully has enough for you to help further as I am a little lost.

[mtail.out.gz](https://github.com/google/mtail/files/2521588/mtail.out.gz)

**Comment by PsychoSid** [comment]
Hi,

Thanks for the help I found the issue where occasionally on 304 responses the bytes received was "-" instead of a integer value. Now ignore these in the parser.

Appreciate the help.

**Comment by jaqx0r** [comment]
Aha, great.

See
https://github.com/google/mtail/blob/master/examples/apache_common.mtail#L15
for the example apache_common program doing the same thing.
