### ISSUE TITLE
fsnotify queue overflow

### ISSUE THREAD

**Issue by renchili** [google/mtail#195]
### OS version
```BASH
Linux 4.15.0-21 #22~16.04.1+2

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
### mtail version
```BASH
mtail version v3.0.0-rc16 
git revision 77eeba903db0ffd90e29c1ee778fdefb0112bfab 
go version go1.11
```
#### what happened
run some times then get a ERROR log as:
```BASH
Log file created at: 2018/11/23 13:44:28
Running on machine: mesos-lb-sg-test-1
Binary: Built with gc go1.11 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1123 13:44:28.621495   22659 log_watcher.go:85] fsnotify error: fsnotify queue overflow
E1123 14:08:29.405245   22659 log_watcher.go:85] fsnotify error: fsnotify queue overflow
E1123 14:16:56.198800   22659 log_watcher.go:85] fsnotify error: fsnotify queue overflow
```
and at then counters are not anymore ++

**Comment by jaqx0r** [comment]
I've been reading https://lwn.net/Articles/605128/ and I can see that https://github.com/fsnotify/fsnotify/blob/master/inotify.go#L251 doesn't implement the refresh pattern recommended in the article.

**Comment by renchili** [comment]
this problem I have tested with 263 concurrent tailing files and each files will increasing 100-1000 lines  per second

**Comment by renchili** [comment]
afterward the mtail just holding the counter unchanged  and not update in time change

**Comment by jaqx0r** [comment]
This doesn't help you but the problem is in the fsnotify library, though
I'm sure we can try to work around it in mtail.

The Linux kernel inotify queue is on my system 16384 entries long.  I am
going to assume yours is too, but you can check it by catting that proc
file I mentioned above.  When you see this error, your kernel has queued up
16384 events in the queue and mtail hasn't processed them all yet --
possibly it's still in the process of *reading* the logs from the last
inotify events!

This is exciting, you're the first to report this issue and then I suppose
you're also the first to have so many files being watched by mtail.

The first workaround I can think of is to split up mtail into separate
processes with fewer log files being watched by each process.  This will
mean fewer events on the queue and more likelihood that mtial will be able
to process all the events.

(Can you share the commandline of mtail you use?  I'm wondering if this is
a greedy glob pattern that has matched too many files and you don't need
them all, perhaps?)

The longer term fix, I suppose, could be to:
* patch fsnotify upstream to handle the case where the queue overflow error
arrives per the linux journal article
* have mtail "disable interrupts" while it's processing log lines -- so
there's no events arriving because it already knows it's busy -- and then
turn back on when the files are all read to end-of-file.

I've been toying with the idea of making a bimodal tailer -- one that can
go into polling mode at high log line rates and back into event mode at low
rates, but in another bug (#157) we got spuport for polling mode
independent of event watching, and in #197 I see that fsnotify doesn't even
work for some users.

Given all that, a bimodal tailer is even overkill, perhaps it's time to
dump fsnotify entirely and just poll the filesystem every 250ms.

In the meantime, can you configure mtail with fewer log files to watch?

**Comment by renchili** [comment]
### cmd for running mtail
```BASH
/usr/bin/mtail_v3.0.0-rc16_linux_amd64 -port 9194 -progs /etc/mtail/conf.mtail -logs /var/log/nginx/*.error.log
```

well I can indeed run few files but in production env that is what we need to monitoring exactly 
our nginx is dynamic configured by reading configuration from auto assembling jenkins job, each time update nginx file there may be new domains that means more files so to be easy I choosed using *

I prefer not  run more than one mtail master process because it was start by inscription in systemd with service file and reporting to prometheus with specific metrics if we run more than one mtail it will be far more difficult to build configuration files that let prometheus know which metrics rule is the same instance (different port means different instance to watch)

**Comment by renchili** [comment]
hi there  I change to polling every 250ms and watching for a few days , it did improve performance but still have   fsnotify over flow error
```BASH
... E1205 09:27:04.200838   17077 log_watcher.go:85] fsnotify error: fsnotify queue overflow
```

**Comment by jaqx0r** [comment]
Once you have polling turned on, these messages shuold be harmless --
they're effectively being bypassed by having the regular poll now.  I
expect your mtail is now able to report metrics after the overflow messages
show up?

I need to write some code to let you disable fsnotify, and I'm now
convinced it's no longer necessary to use fsnotify at all, so I'll have to
do a cleanup of all that code.

**Comment by renchili** [comment]
I do not think when I using polling mode it will be ok. 
I have try with nginx log files that will rotate every 0:00 and I have see some thing like this 
![screen shot 2018-12-07 at 11 47 03 am](https://user-images.githubusercontent.com/33677006/49626724-257d6700-fa16-11e8-98ee-78d097484365.png)
file was deleted but mtail some how still keep fd open
when time pass this signal will accumulate up till fsnotify overflow ?

**Comment by dgonzalezruiz** [comment]
I am also experiencing the same issue, with similar or bigger logfiles / streams. In my case, rsyslogd prints the udp stream into files which are constantly watched by mtail. I wasn't able to find weird file descriptors as pointed above, though.

Tuning the inotify queue didn't seem to work for me either, so far.

**Comment by dgonzalezruiz** [comment]
Enabling polling didn't make these messages go away but it does seem to have improved stability. Still, the mtail instance that has the more traffic in my setup is going unresponsive after some time.

**Comment by jaqx0r** [comment]
You can now turn off fsnotify entirely so that should help more with
stability.

I have a bug open to garbage collect old file descriptors, thanks for the
reminder.

**Comment by jaqx0r** [comment]
Please try the latest tag v3.0.0-rc22 ; I believe that this is now functionally complete enough to disable fsnotify.

**Comment by jaqx0r** [comment]
rc22 had a segfault, rc23 should address all the open features in this bug:

- old file descriptor cleanup to reduce long term memory use: no action required to use, deaults to cleanup every hour, for files older than 24 hours
- disable fsnotify entirely, and use polling mode instead: `--disable_fsnotify` deafults to 250ms poll interval, change with `--poll_interval`
