### ISSUE TITLE
Tailing the specific format of the log files (using glob pattern) with --logs flag 

### ISSUE THREAD

**Issue by jakirpatel** [google/mtail#203]
Mtail version: mtail_v3.0.0-rc18_darwin_amd64
I am using the mtail to extract the metrics from the log files. The current format of the  logfile is : 
datatime-appname-memory.txt 

For example: 
2018112610-memory-status.txt

I want to read the all files *-memory-status.txt through mtail. As our application is writing into different files differentiated by time in filename I want to tail the new file which will be created by app and the logs will be written there. 

Is it possible with mtail to do following , 
`./mtail --progs myprog.mtail --logs log/*-memory-status.txt `

I tried but mtail is not able to read all the files. And even after POST startup mtail is not detecting the new file. Any solution on this?

**Comment by jakirpatel** [comment]
@jaqx0r any comments on this issue ?

**Comment by jaqx0r** [comment]
Per https://github.com/google/mtail/blob/master/docs/Troubleshooting.md, mtail writes its own log to /tmp/mtail.INFO by default.   One of the first things it logs is the commandline, for example:

I0130 20:49:31.271994  237137 main.go:93] Commandline: ["./mtail" "--logs" "/tmp/logs/*" "--progs" "examples"]

That will tell you what mtail was given, because you haven't escaped the * from the shell in your first post, so you might find that explains why after startup mtail doesn't find new files.

 If you increase the log verbosity by adding the flag

--vmodule=tail=1

you will also see what the glob you are passing matches, with lines like 

I0130 20:52:36.487405  237386 tail.go:161] glob matches: []

indicating what files are being matched on the filesystem by the glob pattern.

W0130 20:52:36.487427  237386 mtail.go:74] No matches for pattern "/tmp/log"

means there was nothing at all.

Let me know what you find.

**Comment by jakirpatel** [comment]
Thank you @jaqx0r . I ll look into it.

**Comment by jnovack** [comment]
@jakirpatel Any follow-up?  If this issue is solved or invalid, please considering closing.  Thank you.

**Comment by jakirpatel** [comment]
I used the symlink approach here. 
Once the new file is created  I am changing the symlink of the file which I am parsing with new symlink. 

@jnovack 

Closing it now.
