### ISSUE TITLE
Unable to use capture groups defined in decorator.

### ISSUE THREAD

**Issue by darkl0rd** [google/mtail#207]
I am unable to work out how to re-use a capture group that is defined in a decorator (which seems to have been made possible in #89).

In the snippet below, I am attempting to use 'nodename' as defined in my syslog decorator, however this does not work. 

```
def syslog {/(?P<date>(?P<legacy_date>\w+\s+\d+\s+\d+:\d+:\d+)|(?P<rfc3339_date>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+[+-]\d{2}:\d{2}))/ +
  /\s+(?:\w+@)?(?P<nodename>[\w\.-]+)\s+(?P<application>[\w\.-]+)(?:\[(?P<pid>\d+)\])?:\s+(?P<message>.*)/ {
    len($legacy_date) > 0 {
      strptime($2, "Jan _2 15:04:05")
    }
    len($rfc3339_date) > 0 {
      strptime($rfc3339_date, "2006-01-02T15:04:05-07:00")
    }
    next
  }
}

@syslog {
  counter kernel_mce_events by nodename
  /kernel: \[[\d.]+\] mce: .*Machine check events logged/ {
    kernel_mce_events[$nodename]++
  }

 ...
 ...
```

I'm running mtail 3.0.0-rc20

Thanks :)

**Comment by darkl0rd** [comment]
It seems, it does work -- my expectation was that the metrics would turn up with '0' as a value when nothing was matched; instead they don't appear at all -- is that intended?

**Comment by jaqx0r** [comment]
Let me answer your question with another question: how could mtail know
which 'nodename' to use as the map key for kernel_mce_events if it hasn't
seen any matches yet?

**Comment by darkl0rd** [comment]
My assumption was, that since the syslog 'decorator' always matches, it would use those.
But, I understand if the regex doesn't match, the variable is never set.

Two questions:
1) Is there a way to initialize them to 0?
2) When matched, the metric is available with the correct value. However, during the next scrape the metric is gone (as it is no longer being matched) - how do I make it drop back to 0 instead?

**Comment by jaqx0r** [comment]
Sorry for the long delay.

The medium sized answer is that because mtail doesn't know the values of the label to use on the metric until it's executed (`$nodename` in your case), it doesn't have any way of constructing a useful thing to export.

Yes, #89 would fix your first question by letting you specify a default `$nodename` at program start.

An alternative, which I don't really want to do because managing persistent state adds more complexity, is to checkpoint the metric storage to disk so that when mtail restarts, you get your old variables.  This is compellin gbecause it makes things work better, and I would also be able to store the log file offsets.  It also introduces new problems.  I don't think this'll happen before the 3.0.0 release is final.

How often does your metric get updated?  I'm curious what is going on when the metric disappears.  Is this a Prometheus scrape and a metric being only updated infrequently?

I made a change a few weeks ago to fix how Prometheus metrics are exported so that they shouldn't disappear by default, but it changes the meaning of the timeseries that `mtail` is exporting.  There's more infomation at 
http://google.github.io/mtail/faq#mtail-isnt-propagating-the-scraped-timestamp-to-prometheus

**Comment by darkl0rd** [comment]
OK, apologies for the late reply - this makes perfect sense, and was very helpful.

The metric in question here are the number of oom-killer invocations. They (luckily) don't occur very regularly (if 1 per week, it's a lot - the goal being getting it to and keeping it on 0).

**Comment by jnovack** [comment]
@darkl0rd Is this still an issue?
