### ISSUE TITLE
expose metrics without timestamp

### ISSUE THREAD

**Issue by roidelapluie** [google/mtail#210]
With a counter, we are now exposing the timestamp in prometheus metrics

Is it something we can avoid?

performance_start_count{action="sending2",op="OP3",prog="bedop.mtail"} 771 *1551220410001*
performance_start_count{action="sending2",op="OP4",prog="bedop.mtail"} 772 *1551220425001*

**Comment by jaqx0r** [comment]
It's by design because the timestamp of the metric comes from the log file,
not the time of Prometheus' scrape.

If you can convince me you want the other behaviour, I can give you a
command line flag to toggle it.

**Comment by roidelapluie** [comment]
Yes but Prometheus will only look at metrics from the last 5 minutes (https://manpages.debian.org/stretch-backports/prometheus/prometheus.1.en.html query.lookback-delta ).

If we have a slow movung counter it will just disappear from prometheus if we expose the timestamp.

**Comment by roidelapluie** [comment]
Also, look @bbrazil 's answer to this question (in another contect): https://groups.google.com/forum/#!msg/prometheus-users/qgxKH6_gYzM/LyO5wGO6BwAJ

**Comment by jaqx0r** [comment]
You've convinced me.  I'm not happy about it, I think prometheus has incorrect behaviour, but we can address that.

**Comment by SuperQ** [comment]
@jaqx0r The idea with Prometheus is that we want the value "at the time Prometheus saw the data", the only reason the timestamps are in the format is for federation ingestion.

**Comment by SuperQ** [comment]
One thing to note, the timestamps when turned on are broken as well, and cause additional behavioral problems.

```
# HELP unicorn_pid_timeouts_total defined at unicorn.mtail:4:9-34
# TYPE unicorn_pid_timeouts_total counter
unicorn_pid_timeouts_total{prog="unicorn.mtail"} 0 0
```

Since no timeouts have been seen, this creates a metric value that only exists at epoch. This is well outside of any sane monitoring system retention range.

This is why we consider the Prometheus behavior of timestamping polled data based on the server time is the right thing to do. Same behavior as the systems that use the `/varz` output. :wink:

**Comment by jaqx0r** [comment]
I see. I'll update the docs to explain.
