### ISSUE TITLE
Delay in processing the logs with mtail polling

### ISSUE THREAD

**Issue by jakirpatel** [google/mtail#214]
We are processing the following things: 

Number of log line per second : 75000
Polling interval: 1s 

For mtail polling I saw the mismatched data in prometheus. I am not sure but I think there is delay in processing such huge amount of log. 

The spike we confirmed was 75k per second but with mtail we only saw the spike of 29k. 
In mtail endpoint there was no error of reading the logfile.

We are running the process with following options: 
The logs are written into NFS here. That means we are reading from the NFS file system. 

```
nice -n 19 /home/mtail \
-poll_interval 1s \
-port 3906 \
-progs progs/accessLogs.mtail \
-logs /prod/access.log \
&
```

How can we get the correct numbers ? Also how to improve the performance in terms of reading the files with 70k lines per second? Your comments will be helpful.

**Comment by jaqx0r** [comment]
Thanks for the report.

You say that mtail didn't have an error, so I presume then mtail did read
every log from the spike, but it took three times as long?  I.e. mtail
peaked at 29k lines per second despite the incoming rate of 75k per second,
meaning that in order to process the backlog it took about 75/29 or 2.5x as
slow.

The numbers are probably correct!  But the mismatch is very much due to the
service time of mtail.

I can imagine the extra latency is due to one or more of the following
factors:
* The mtail program itself does lots of work per line, ie. the service time
per line, perhaps there's a lot of matching required in
progs/accessLogs.mtail ?  Line processing is linear, so mtail needs to wait
for a program to finish before it processes the next line.
* The time mtail takes to stat and read the log lines off disk adds latency
to processing, i.e the IO time per line.  I am confident there's
inefficiencies in the log watcher and tailer subsystem that could be
improved.
* The time it takes for mtail to notice there's new data, the 1s poll
interval, i.e. the wait delay.

The one that I think really matters for handling a burst like this is the
service time, i.e. the actual execution of mtail.

As to how to improve the performance --
I've been waiting for me to get around to using the Prometheus client in
order to correctly instrument this with a latency histogram, which I've
just done last week, so I should start by adding that instrumentation.
 That will let us know roughly where the time is being spent.  (I also want
to add OpenCensus tracing, which can get us more accurate examples of how
the time is spent.)
mtail doesn't yet have a good profiling experience for analysing your own
program for hotspots.  I didn't' initially because I worried that adding
instruction counters would add too much overhead.  I think I'd better
justify that with data, though.

One thing you could do in the meantime if you wanted to get your hands
dirty is try out the Go tracing and profiling tools on an existing
installation.
https://making.pusher.com/go-tool-trace/
https://blog.golang.org/profiling-go-programs

**Comment by jakirpatel** [comment]
@jaqx0r 

Thank you for your reply. I got few more results while testing locally. 



I tested with two different programs and found some good results. 

**1. Program with percentiles enabled.** 
```
counter exalogic_requests_length_bytes by otd, app
counter exalogic_requests_status_count by otd, app, status
counter exalogic_requests_time_seconds_count by otd, app
counter exalogic_requests_time_seconds_sum by otd, app
counter exalogic_requests_time_seconds_bucket by le, otd, app

getfilename() =~ /[^\/]+\/[^\/]+\/otd\/[^\/]+\/net-(?P<otd>[^\/]+)\/logs\/(?P<app>[^-]+)/
def otdlog {
    /\S+\s+\S+\s+\[[^\]]+\]\s+"[^"]+"\s+(?P<status>\d+)\s+(?P<content_length>\d+)\s+\S+\s+(?P<duration>\d+)/ {
    next
    }
}

@otdlog {
        exalogic_requests_length_bytes[$otd][$app] += $content_length
        exalogic_requests_status_count[$otd][$app][$status]++
        exalogic_requests_time_seconds_count[$otd][$app]++
    	exalogic_requests_time_seconds_sum[$otd][$app] += $duration * 0.000001

        # the access log is in microseconds
    	# 5ms bucket
        $duration <= 5000 {
                exalogic_requests_time_seconds_bucket["0.005"][$otd][$app]++
    	} else {
                exalogic_requests_time_seconds_bucket["0.005"][$otd][$app] += 0
        }

    	# 10ms bucket
    	$duration <= 10000 {
        	exalogic_requests_time_seconds_bucket["0.01"][$otd][$app]++
    	} else {
        	exalogic_requests_time_seconds_bucket["0.01"][$otd][$app] += 0
    	}

    	# 25ms bucket
    	$duration <= 25000 {
        	exalogic_requests_time_seconds_bucket["0.025"][$otd][$app]++
    	} else {
        	exalogic_requests_time_seconds_bucket["0.025"][$otd][$app] += 0
    	}

    	# 50ms bucket
    	$duration <= 50000 {
        	exalogic_requests_time_seconds_bucket["0.05"][$otd][$app]++
    	} else {
        	exalogic_requests_time_seconds_bucket["0.05"][$otd][$app] += 0
    	}

    	# 100ms bucket
    	$duration <= 100000 {
        	exalogic_requests_time_seconds_bucket["0.1"][$otd][$app]++
    	} else {
        	exalogic_requests_time_seconds_bucket["0.1"][$otd][$app] += 0
    	}

    	# 250ms bucket
    	$duration <= 250000 {
        	exalogic_requests_time_seconds_bucket["0.25"][$otd][$app]++
    	} else {
        	exalogic_requests_time_seconds_bucket["0.25"][$otd][$app] += 0
    	}

    	# 500ms bucket
    	$duration <= 500000 {
        	exalogic_requests_time_seconds_bucket["0.5"][$otd][$app]++
    	} else {
        	exalogic_requests_time_seconds_bucket["0.5"][$otd][$app] += 0
    	}

    	# 1s bucket
    	$duration <= 1000000 {
        	exalogic_requests_time_seconds_bucket["1"][$otd][$app]++
    	} else {
        	exalogic_requests_time_seconds_bucket["1"][$otd][$app] += 0
    	}

    	# 2.5s bucket
    	$duration <= 2500000 {
        	exalogic_requests_time_seconds_bucket["2.5"][$otd][$app]++
    	} else {
        	exalogic_requests_time_seconds_bucket["2.5"][$otd][$app] += 0
    	}

    	# 5s bucket
    	$duration <= 5000000 {
        	exalogic_requests_time_seconds_bucket["5"][$otd][$app]++
    	} else {
        	exalogic_requests_time_seconds_bucket["5"][$otd][$app] += 0
    	}

    	# 10s bucket
    	$duration <= 10000000 {
        	exalogic_requests_time_seconds_bucket["10"][$otd][$app]++
    	} else {
        	exalogic_requests_time_seconds_bucket["10"][$otd][$app] += 0
    	}

    	# 15s bucket
    	$duration <= 15000000 {
        	exalogic_requests_time_seconds_bucket["15"][$otd][$app]++
    	} else {
        	exalogic_requests_time_seconds_bucket["15"][$otd][$app] += 0
    	}

    	# "inf" bucket, also the total number of requests.
    	exalogic_requests_time_seconds_bucket["+Inf"][$otd][$app]++

}
```


Conclusion:The max number of lines parsed by this program was 25k. 


**2. Program without percentiles enabled.** 

```
counter exalogic_requests_status_count by otd, app, status
counter exalogic_requests_time_seconds_count by otd, app

getfilename() =~ /[^\/]+\/[^\/]+\/otd\/[^\/]+\/net-(?P<otd>[^\/]+)\/logs\/(?P<app>[^-]+)/
def otdlog {
    /\S+\s+\S+\s+\[[^\]]+\]\s+"[^"]+"\s+(?P<status>\d+)\s+(?P<content_length>\d+)\s+\S+\s+(?P<duration>\d+)/ {
    next
    }
}

@otdlog {
        exalogic_requests_status_count[$otd][$app][$status]++
        exalogic_requests_time_seconds_count[$otd][$app]++

}
```

Conclusion: The max number of lines parsed by this program was 80k. 


Is there any way to improve the first program?

**Comment by jaqx0r** [comment]
That's very interesting.

I've just pushed a merge that introduces a new syntax for histograms.  Would you like to try it out?

Replacing all your histogram code with:

```
histogram exalogic_requests_time seconds buckets 5000, 10000, ..., by otd, app

@otdlog {
  exalogic_requests_time_seconds[$otd][$app] = $duration
}
```

**Comment by jakirpatel** [comment]
@jaqx0r  Did you released it with new mtail version? If yes could you please confirm with which version ? I ll try it out. 

Also I was wondering about how the timestamp of the logs work with mtail and timeseries ? 
1. If I am using the log timestamp and if the delay in processing happens. Then how it will be treated in time series. I am using prometheus for time series.

**With my observation the data points  with respect to time will be incorrect as prometheus does not know that it needs to look for log timestamp while processing.** (Or it would have already written the data points particular time)

**Comment by jakirpatel** [comment]
@jaqx0r 

I used your new histogram syntax. Seems the performance is improved **3.5x** for me. I seen the peak of traffic till 65k. 

**Number of lines parsed per second : 50k +** 

However I feel the profiling of mtail program and max number of lines can get parsed with particular program and log file (including other factors polling / fnotify and file system)will be good feature to get added. 

About new histogram syntax: 
I think we are not maintaining the correct histogram values. The **histogram_quantile()** function returned the **NAN** value to me. 

So I checked more details that why it returned the NAN value. According to the prometheus document related with the histogram , 

https://prometheus.io/docs/concepts/metric_types/#histogram

> the count of events that have been observed, exposed as <basename>_count (identical to <basename>_bucket{le="+Inf"} above)

This means the bucket value for {le="+Inf"} must be same as basename_count. However we are not maintaining it in the same way.

**Comment by jaqx0r** [comment]
Thanks for the report. The tests do not yet cover full end to end metrics
transfer to Prometheus, so I should work on that to ensure this doesn't
happen again.

**Comment by jakirpatel** [comment]
> @jaqx0r Did you released it with new mtail version? If yes could you please confirm with which version ? I ll try it out.
> 
> Also I was wondering about how the timestamp of the logs work with mtail and timeseries ?
> 
> 1. If I am using the log timestamp and if the delay in processing happens. Then how it will be treated in time series. I am using prometheus for time series.
> 
> **With my observation the data points with respect to time will be incorrect as prometheus does not know that it needs to look for log timestamp while processing.** (Or it would have already written the data points particular time)

@jaqx0r any opinion about the timestamp ?

**Comment by jaqx0r** [comment]
Yeah.  The advice from Prometheus is that it ignores any timestamp exported
from mtail, preferring it's own scrape time.  Any log timestamp parsed is
ignored, and the time after the processing delay is used by Prometheus.

Because of the potential processing delay, mtail offers the ability to
extract and export the timestamp because that's the closest time to when
the event actually occurred that mtail knows about.  But it seems that it's
not supported by Prometheus to use that timestamp on infrequently changing
values.  See
https://github.com/google/mtail/blob/master/docs/faq.md#mtail-isnt-propagating-the-scraped-timestamp-to-prometheus
for more details on this.

I don't like it, but it does mean that if you want to squeeze more
performance out of mtail, you can remove any timestamp parsing code from
your program.

I haven't yet written the code to add the mtail delay instrumentation, but
it is next in my queue.

The histogram code is not yet tagged with a release version, but I can go
and do that now.

**Comment by jaqx0r** [comment]
OK, the release tagged v3.0.0-rc26 has the histogram type in it  (but not
the delay instrumentation.)

**Comment by jakirpatel** [comment]
Thank you @jaqx0r 

For histogram should I expect the +Inf bucket should be as <basename>_count ? Are you adding that patch as well?

**Comment by jaqx0r** [comment]
Oh dear. I forgot that part in my excitement.

**Comment by jakirpatel** [comment]
> Thank you @jaqx0r
> 
> For histogram should I expect the +Inf bucket should be as _count ? Are you adding that patch as well?

If the +Inf bucket is not maintaining the right value then it seems it will broke my current setup of histogram_quantile() function. Previously the value was same as basename_count bucket for {le="+Inf"} bucket.

**Comment by jakirpatel** [comment]
@jaqx0r 

I observed one more scenario where mtail worked in unusual way. 

Following are the points: 


1. I was reading the 32 files with a single mtail process. But out of 32 at a time the logs were written only into 16 files. The process was polling with 1s interval through NFS filesystem. 

2. What I saw is during the high traffic I faced latency with mtail. 

3. Also mtail processe went into some state where I was not able to kill the process with `kill pid`

4. However I was able to kill it forcefully. `kill -9 pid`


I think mtail should add instrumentation to test such scenarios where we are reading N number of log files with Y number of lines get parsed.

**Comment by jaqx0r** [comment]
In your last comment, are you saying that mtail should have read 32 files but instead only read 16 of them?   
 Or that it correctly didn't read from 16 that weren't being written to?

I don't understand what you think should have happened.

**Comment by jaqx0r** [comment]
The last commit doesn't fix this bug yet, sorry.  I assumed iterating over keys in a map was stable, it's not.

**Comment by jaqx0r** [comment]
There is now a histogram of VM processing time exported, per program.  Let me know how it goes for you -- I suspect the bucket boundaries need tweaking.

**Comment by jakirpatel** [comment]
> In your last comment, are you saying that mtail should have read 32 files but instead only read 16 of them?
> Or that it correctly didn't read from 16 that weren't being written to?
>
> I don't understand what you think should have happened.

Here is explanation: 

There are total 64 files to read. But the logs get written into only 32 files at single instance. I observed if I am reading 32 files at a time with single mtail process I faced the huge delay (more than half hour). 

I was not able to kill the mtail process at same time. however forceful killing worked (which we dont usually use). 

So for mtail processing its necessary to understand how many files we can read with % of latency. If I have n number of files with m number of lines then how many mtail processes should be used. Also how the multithreading works while using the CPU resources.

**Comment by jakirpatel** [comment]
> > Thank you @jaqx0r
> > For histogram should I expect the +Inf bucket should be as _count ? Are you adding that patch as well?
> 
> If the +Inf bucket is not maintaining the right value then it seems it will broke my current setup of histogram_quantile() function. Previously the value was same as basename_count bucket for {le="+Inf"} bucket.

@jaqx0r Is this solved with the latest commit ? If yes I ll build and test it.

**Comment by jaqx0r** [comment]
> > > Thank you @jaqx0r
> > > For histogram should I expect the +Inf bucket should be as _count ? Are you adding that patch as well?
> > 
> > 
> > If the +Inf bucket is not maintaining the right value then it seems it will broke my current setup of histogram_quantile() function. Previously the value was same as basename_count bucket for {le="+Inf"} bucket.
> 
> @jaqx0r Is this solved with the latest commit ? If yes I ll build and test it.

yes, the histogram count == +Inf bug is fixed in the latest commit, and also there is now a histogram called `mtail_vm_line_processing_duration_milliseconds` that shows how long it takes for the VMs to process incoming lines.

OK there's two other issues I think:

- You have two instances of `mtail` running, each reading 32 of 64 total files, and at 32 files `mtail` takes about half an hour to process a backlog of data.
- You can't SIGTERM an `mtail` process -- or at least it looks like it isn't responding.

Let's cover the second problem first -- if you look in the INFO log, mtail will notify you that it has received the termination signal.  If that's not there at all, then I'm very worried.  If it is there,and it hasn't actually stopped, I think it's trying to finish processing any lines that are already read rather than stop immediately.

Do you think it's better to try to process what we can, and then quit, or to just stop?

The first problem, that you want to understand how fast an mtail can be?  Let me start with another problem:  `mtail` can't know how backlogged it is, it only knows that there are either lines to read or not yet lines to read, and will try to read as much as it can per file.  This might be causing starvation amongst 32 files with high line rates, which is.. another problem.
The effect of this is that it's very difficult to know how long it takes mtail to respond, or what the backlog is.  We can only observe it after the fact.  As of an hour ago, `mtail` has the histogram showing how long it takes for the user supplied program to process the lines.  I do also want to add instrumentation of the line latency from the moment it's read, though, which is the absolute best we can know about the size of the backlog.

Your final question unravels somethign else: `mtail` is basically single-threaded per VM.  Each program is run only once, and processes lines serially.  It should be possible to increase the number of "threads" and process more than one line concurrently.

I'd like to make some of these into separate issues, to make it easier to work on.

For the immedate future, can you run more mtail processes?  Have fewer logs being watched per mtail?  If you can now get 25k lines per second, then maybe running 4 instead of 2 is going to help you in the short term.

**Comment by jakirpatel** [comment]
@jaqx0r 

Thanks for your comment. I already changed mtail to watch fewer files. I ll be having load test to check its performance. 


mtail_vm_line_processing_duration_milliseconds  This will help me a lot. Thank you for that. I ll let you know once I finish my testing.

**Comment by jakirpatel** [comment]
@jaqx0r 

I performed few more tests. For one of our app we ll have the 50k + log lines.

Configuration of my mtail process:
```
./mtail \
-poll_interval 1ms \
-port 3501 \
-progs progs/logs.mtail \
-logs /rms/prod/otd/302/net31/logs/testlogfile \
&
```

logs.mtail:
```
counter exalogic_requests_length_bytes by otd, app
counter exalogic_requests_status_count by otd, app, status

#Adding the new histogram syntax
histogram exalogic_requests_time_seconds buckets -1, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 15 by otd, app

#Getting the filename: This will differentiate with the OTD
getfilename() =~ /[^\/]+\/[^\/]+\/otd\/[^\/]+\/net-(?P<otd>[^\/]+)\/logs\/(?P<app>[^-]+)/

def logp {
    /\S+\s+\S+\s+\[[^\]]+\]\s+"[^"]+"\s+(?P<status>\d+)\s+(?P<content_length>\d+)\s+\S+\s+(?P<duration>\d+)/ {
    next
    }
}

@logp {
        exalogic_requests_length_bytes[$otd][$app] += $content_length
        exalogic_requests_status_count[$otd][$app][$status]++
    	exalogic_requests_time_seconds[$otd][$app] = $duration * 0.000001
}

```

<img width="1409" alt="Screen Shot 2019-04-12 at 11 54 02" src="https://user-images.githubusercontent.com/31799856/56009488-df654680-5d1a-11e9-9fbf-c31e1acc199e.png">

RED: The highest one for peak around 40k+. we saw huge delay while processing the logs.  In Red ones.

logs.mtail:
```
counter exalogic_requests_status_count by otd, app, status

#Getting the filename: This will differentiate with the OTD
getfilename() =~ /[^\/]+\/[^\/]+\/otd\/[^\/]+\/net-(?P<otd>[^\/]+)\/logs\/(?P<app>[^-]+)/

def logp {
    /\S+\s+\S+\s+\[[^\]]+\]\s+"[^"]+"\s+(?P<status>\d+)\s+(?P<content_length>\d+)\s+\S+\s+(?P<duration>\d+)/ {
    next
    }
}

@logp {
        exalogic_requests_status_count[$otd][$app][$status]++
}

```
GREEN: For green ones I removed the histogram from program and we saw delay as well.  Is there any possibility if we have some benchmark. Or can we improve the performance of mtail somehow so it can  parse more than 50k+ lines  ?


Please let me know your opinions.

**Comment by jakirpatel** [comment]
> @jaqx0r
> 
> I performed few more tests. For one of our app we ll have the 50k + log lines per second.
> 
> Configuration of my mtail process:
> 
> ```
> ./mtail \
> -poll_interval 1ms \
> -port 3501 \
> -progs progs/logs.mtail \
> -logs /rms/prod/otd/302/net31/logs/testlogfile \
> &
> ```
> logs.mtail:
> 
> ```
> counter exalogic_requests_length_bytes by otd, app
> counter exalogic_requests_status_count by otd, app, status
> 
> #Adding the new histogram syntax
> histogram exalogic_requests_time_seconds buckets -1, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 15 by otd, app
> 
> #Getting the filename: This will differentiate with the OTD
> getfilename() =~ /[^\/]+\/[^\/]+\/otd\/[^\/]+\/net-(?P<otd>[^\/]+)\/logs\/(?P<app>[^-]+)/
> 
> def logp {
>     /\S+\s+\S+\s+\[[^\]]+\]\s+"[^"]+"\s+(?P<status>\d+)\s+(?P<content_length>\d+)\s+\S+\s+(?P<duration>\d+)/ {
>     next
>     }
> }
> 
> @logp {
>         exalogic_requests_length_bytes[$otd][$app] += $content_length
>         exalogic_requests_status_count[$otd][$app][$status]++
>     	exalogic_requests_time_seconds[$otd][$app] = $duration * 0.000001
> }
> ```
> <img alt="Screen Shot 2019-04-12 at 11 54 02" width="1409" src="https://user-images.githubusercontent.com/31799856/56009488-df654680-5d1a-11e9-9fbf-c31e1acc199e.png">
> 
> RED: The highest one for peak around 40k+. we saw huge delay while processing the logs. In Red ones.
> 
> logs.mtail:
> 
> ```
> counter exalogic_requests_status_count by otd, app, status
> 
> #Getting the filename: This will differentiate with the OTD
> getfilename() =~ /[^\/]+\/[^\/]+\/otd\/[^\/]+\/net-(?P<otd>[^\/]+)\/logs\/(?P<app>[^-]+)/
> 
> def logp {
>     /\S+\s+\S+\s+\[[^\]]+\]\s+"[^"]+"\s+(?P<status>\d+)\s+(?P<content_length>\d+)\s+\S+\s+(?P<duration>\d+)/ {
>     next
>     }
> }
> 
> @logp {
>         exalogic_requests_status_count[$otd][$app][$status]++
> }
> ```
> GREEN: For green ones I removed the histogram from program and we saw delay as well. Is there any possibility if we have some benchmark. Or can we improve the performance of mtail somehow so it can parse more than 50k+ lines ?
> 
> I also see there are additional metrics like gc , memstats and mtail_vm_processing. Do you recommend by removing all additional metrics will improve the performance?
> 
> Please let me know your opinions.

@jaqx0r 


Any option for mtail if I dont want to expose the state of mtail itself. I just want the most of processing time should be used for application log processing and exposing the metrics.

**Comment by jaqx0r** [comment]
Have you tried a later version of `mtail`?  I believe the issues are all addressed now.
