### ISSUE TITLE
Act as a syslog collector

### ISSUE THREAD

**Issue by Xaelias** [google/mtail#216]
Hi,

I was wondering if maybe there was any plan to support other source than text files. Something like being able to configure mtail as a syslog "collector" would be really useful (to me).

Thanks

**Comment by jaqx0r** [comment]
You can have mtail listen to a named pipe instead of tailing a file.  Just
specify the path to the pipe and it should just work.

**Comment by Xaelias** [comment]
(excuse the newb question, that's a part of Linux I'm not so familiar with)
So are you saying something like creating a named pipe with `mkfifo /path/to/named/pipe` and then doing something like `socat TCP-LISTEN:514 PIPE:/path/to/named/pipe`?  
Thanks!

**Comment by jaqx0r** [comment]
Ah, yes. I was thinking of configuring the local syslog daemon to write to
a named pipe instead of socat, but that would work I think.

However, have a look at rsyslog for managing transfer of logs over the
network between systems.  I don't want to add syslog support directly to
mtail because I think tools like rsyslog do it better.

**Comment by Xaelias** [comment]
Thanks I appreciate the help!

**Comment by jaqx0r** [comment]
No problem!
