### ISSUE TITLE
Pattern expressions with no action block can poison the scope with nonexistent capref variables

### ISSUE THREAD

**Issue by arrow2012** [google/mtail#284]
nginx.mtail

counter request_count          by host, request_uri, status as "nginx_request_count"
counter nginx_log_nomatch_count
/"(?P<host>\S+)" ;;; "(?P<request_uri>\S+)" ;;; (?P<status>\d{3}) ;;; (?P<request_time>\S+) ;;; (?P<upstream_response_time>\S+) ;;; (?P<upstream_addr>\S+) ;;; (?P<upstream_status>\S+)/
/$/ {
    request_count[$host][$request_uri][$status]++
} else {
    nginx_log_nomatch_count++
}

nginx log like this:

"abc.123.com" ;;; "/wechat/query_class" ;;; 204 ;;; 0.001 ;;; 0.001 ;;; "192.168.20.109:9007" ;;; 204
"abc.123.com" ;;; "/clazzes/943b46bf-8de6-41ac-b5d0-d96b4979c53a/teacher_com" ;;; 204 ;;; 7.164 ;;; 7.160, 0.004 ;;; "192.168.20.105:9203, 192.168.20.153:9201" ;;; 502, 204"

nginx.mtail: Runtime error: panic in thread &vm.thread{pc:6, matched:false, matches:map[int][]string{0:[]string(nil), 1:[]string{""}}, time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, stack:[]interface {}{false}} at instr "{capref 1 7}": runtime error: index out of range
I0103 14:12:41.381467   18425 vm.go:93] Error occurred at instruction 5 {capref, 1}, originating in nginx.mtail at line 8

the line 2   contains with two upstream_addrs ,and mtail parse faild,  and it cannot work

**Comment by jaqx0r** [comment]
I'll assume your question is why is this happening?

It looks like we have lost some linebreaks.

What is line 8 in the program?  Capref 1 is probably $host or $status when
indexing the request_count map, which are not defined in the pattern.

 I'm confused why this compiled tho because it should have given you a
compile time error instead of a runtime error.  I'll try to reproduce that.

**Comment by jaqx0r** [comment]
I managed to reconstruct your program:

```
counter request_count by host, request_uri, status
counter nginx_log_nomatch_count
/"(\S+)" ;;; "(?P<request_uri>\S+)" ;;; (\d{3}) ;;; (?P<request_time>\S+) ;;; (?P<upstream_response_time>\S+) ;;; (?P<upstream_addr>\S+) ;;; (?P<upstream_status>\S+)/
/$/ {
  request_count[$upstream_addr, $request_uri, $upstream_status]++
  } else {nginx_log_nomatch_count++
}
```

The first weird thing is you have two blocks; the newline at the end of "upstream_status>\S+)/" ends that statement, and then the /$/ is on the next line.  This is confusing!

I think that unattached pattern expression must be putting the capture group references in scope, incorrectly.

So when the request_count line is executed, there isn't any value on the capture group reference called upstream_addr or request_uri or upstream_status, because they shouldn't exist.

This then fails in the VM when trying to look them up, then crashes.

**Comment by jaqx0r** [comment]
The smallest reproductoin case I have is

```
counter c by x
/"(?P<x>\S+)"/
/$/ {
  c[$x]++
}
```
and echo any non-" character to the log.

**Comment by jaqx0r** [comment]
I was wondering how to fuzz end-to-end like this, and figure I can reuse the existing fuzzer, and separate the data input at a magic character (as per https://github.com/google/fuzzing/blob/master/docs/split-inputs.md).  The existing corpus doesn't have that character, so the effective test is the same as the current test -- compile only and catch regression.

**Comment by jaqx0r** [comment]
As for the fix, I've managed to instrument the type checker and proven that my guess is right, the symbols are being added to the top level scope; they should only be added to a scope inside a conditional statement with a pattern expr.

**Comment by jaqx0r** [comment]
A form like

`/x/ { }`

matches the `conditional_statement` rule 

while 

`/x/`

without a trailing compound_statement goes via the `expression_statement.`  Both have a `match_expr` in the tree, which the `/x/` fits.


Here's the first form's trace, 
```
reduce 86 in:
	state-165
reduce 55 in:
	state-42
reduce 54 in:
	state-30
reduce 49 in:
	state-26
reduce 25 in:
	state-22
reduce 2 in:
	state-49
reduce 17 in:
	state-16
reduce 5 in:
	state-5
reduce 3 in:
	state-3
```

and the second form's trace:

```
reduce 86 in:
	state-165
reduce 55 in:
	state-42
reduce 54 in:
	state-30
reduce 49 in:
	state-26
reduce 25 in:
	state-22
reduce 21 in:
	state-14
reduce 20 in:
	state-23
reduce 18 in:
	state-53
reduce 5 in:
	state-5
reduce 3 in:
	state-3
```

the first goes via states 26, 22, ..., 47, 5; consider this inverted parse tree:

26: `match_expr -> pattern_expr`
22: `logical_expr -> match_expr`
(parse block)
47: `conditional_statement -> logical_expr compound_statement`
4: `stmt -> conditional_statement`
3: `stmt_list -> stmt_list stmt`
...
5: `stmt -> expression_stmt`

and the second goes via state 26, 22, 14, 23, 53, 5; consider this inverted parse tree:

26: `match_expr -> pattern_expr`
22: `logical_expr -> match_expr`
14: `assign_expr -> logical_expr`
23: `expr -> assign_expr`
53: `expression_statement -> expr NL`
5: `stmt -> expression_stmt`

The `expression_statement` seems to be too greedy.  It captures all newlines, so ends up being invoked here in both paths.  I'd expect the former to only show up for a conditional_statement and then fail because there's no {} after, so I need to look at the parse tree along both pathways.

**Comment by jaqx0r** [comment]
Well that was hard work, but now it's fixed.

Thanks for the report!
