### ISSUE TITLE
mutil condition not working well

### ISSUE THREAD

**Issue by arrow2012** [google/mtail#286]
const UUID /(?P<uuid>\w{8}(-\w{4}){3}-\w{12})/
counter nginx_log_nomatch_count
counter cond_all
counter nginx_1
counter nginx_2
counter nginx_3

/"(?P<host>[\s\S]*)" ;;; "(?P<uri>[\s\S]*)" ;;; (?P<status>[\s\S]*) ;;; (?P<request_time>[\s\S]*) ;;; (?P<upstream_response_time>[\s\S]*) ;;; "(?P<upstream_addr>[\s\S]*)" ;;; (?P<upstream_status>[\s\S]*)/ {
  $uri =~ /^\/gkids\/report\// + UUID {
  nginx_1 ++
  }
  $uri =~ /^\/gkidshow\/class\/picture_book\// + UUID {
  nginx_2 ++
  }
  $uri =~ /^\/gkids\/class\/picture_book\// + UUID {
  nginx_3 ++
  } else {
  cond_all ++
  }

} else {
    nginx_log_nomatch_count++
}

there are 36 line in the log

nginx_1{prog="nginx.mtail"} 2

nginx_2{prog="nginx.mtail"} 3

nginx_3{prog="nginx.mtail"} 2

cond_all{prog="nginx.mtail"} 34

but  34 lines match else condtion ,it is not right

maybe the else conditon only work with condition 3
the else condtion should be 36-2 -3 -2 = 29 lines

**Comment by jaqx0r** [comment]
The else is only associated with the final match expression.  The behaviour
you want you can get by changing it to an "otherwise" inside that first
nested block statement, "otherwise" means "only if no other matches
succeeded inside this block."

Please read more at
https://github.com/google/mtail/blob/master/docs/Language.md#otherwise-clauses
