### ISSUE TITLE
language: Add function to perform string replacement

### ISSUE THREAD

**Issue by TheDJVG** [google/mtail#326]
I don't think this is a problem in mtail but more of a "not sure how to do this". The problem is that rsync logs the bytes with a comma (,) in the total and I'm trying to convert this into an integer.

I have the following log line:
```bash
Jun 28 20:44:32 backup rsync[3996]: sent 642,410,725 bytes  received 14,998,522,122 bytes  497,002.00 bytes/sec
```
And based on the `rsyncd.mtail` example I have now this:
```mtail
/sent (?P<sent>[\d,]+) bytes  received (?P<received>[\d,]+) bytes/ {
    # Sum total bytes across all sessions for this process
    bytes_total["sent"] += $sent
    bytes_total["received"] += $received
```

And this creates the metrics like this:
```json
  "bytes_total": [
    {
      "Name": "bytes_total",
      "Program": "rsyncd.mtail",
      "Kind": 1,
      "Type": 2,
      "Keys": [
        "pid"
      ],
      "LabelValues": [
        {
          "Labels": [
            "sent"
          ],
          "Value": {
            "Value": "642,410,725",
            "Time": 1593389595338436176
          }
        },
        {
          "Labels": [
            "received"
          ],
          "Value": {
            "Value": "14,998,522,122",
            "Time": 1593389595338437666
          }
        }
      ]
    }
  ]
```
I'm struggling on what the correct way is to remove the ',' and convert it to an integer using int(). I thought about adding additional capture groups inside the sent/received capture group and glue them together but this didn't seem to work. Help is greatly appreciated!

**Comment by jaqx0r** [comment]
Yeah it's quite difficult.  The way that might work is t have separate
capture group choices depending on how many commas there are, and to
add/multiply the groups together.

The Go integer parser doesn't like commas which is why the simple option
doesn't work.  I think there's already a bug about this, but it means
writing our own integer parser, which I've been reluctant to do yet :)

**Comment by TheDJVG** [comment]
Thanks for the answer! Would be adding a `str_replace` function a solution?

```
    bytes_total["sent"] += int(str_replace($sent, ',', ''))
    bytes_total["received"] += int(str_replace($received, ',', ''))
```

But this might be too expensive. Maybe I'll should do a dirty trick and add a filter on the log writer that removes any ',' when the file is written. Thanks for the reply anyway!

**Comment by jaqx0r** [comment]
I think we can do that, I don't like it but it'll work :)

**Comment by AARON327** [comment]
Any updates on this?

**Comment by jaqx0r** [comment]
Re parsing an int with commas, this is very similar to #424 and in both cases I think `mtail` is going to need custom parsers, which means it's going to require some more thought because the idea of allowing a comma in a regular integer probably has some edge cases I've not thought of yet... no I've thought of one, what if we're reading a comma separated file?

If we had a `str_replace` then we avoid that problem, because the prograam writer gets to decide when to use it. It'd return a type string, and we'd need another cast to int after.  Not so bad I expect.  We could also have a convenience method that did both -- automatically read fancy integers and strip out commas or decimal points depending on locale and return an Int type, but maybe that is overkill.
