### ISSUE TITLE
Store.Expire() generates 

### ISSUE THREAD

**Issue by rafaelpirolla** [google/mtail#341]
mtail version v3.0.0-rc38 git revision 0601c73197c5e314dcf3e27218de8f8ad5a83691 go version go1.15.2 go arch amd64 go os linux

I was having issues with fsnotify (>10k rps) and switched to polling and that solved half of the issues.

Now some of the times Store.Expire() runs I am getting spikes in the metrics:
![image](https://user-images.githubusercontent.com/10890089/99777026-02b8c000-2b12-11eb-996a-d6d8f5949527.png)

Logs shows nothing except:

store.go:107] Running Store.Expire()
log_watcher.go:294] Found this processor in watched list
log_watcher.go:289] No abspath in watched list, added new one for ...

I'm unsure how to debug the issue.

**Comment by jaqx0r** [comment]
Expiration holds a lock on the metrics store, that would manifest as a
spike in, perhaps, latency of metrics delivery. You haven't said what this
chart is showing so I can't guess any further what might be going on.

The next release of mtail removes fsnotify entirely btw.

**Comment by rafaelpirolla** [comment]
It is a counter in http access log file. This plot is the rate.

**Comment by jaqx0r** [comment]
I think I understand: you think mtail is stalling so for one moment it
underreports the rate and the next moment it overreports as the counter
catches up.

A general fix for this is to compute your rates over a longer period to
smooth over any burstiness.

Meanwhile we'll leave this bug open to see if the metrics expiration can be
done without holding a lock on the whole database.

**Comment by tomiloza** [comment]
I am working with @rafaelpirolla together on this issue.  
As correctly assumed the cleanup of the memory objects takes longer, as we probably have around 10 000 entries in the metrics map. The current implementation of the Gc function hast three nested loops, giving a potential worst time complexity of  O(n3).  Additional as you mentioned the problem is that there is a lock on the whole database and not on a single entry while checking the expiration time. Currently we have done a workaround to change the time interval of the cleanup  to 72h, as we expect that only 1% of the metrics will really expire. Changing the rate interval we will have a smoother spike in our graphs, but still we will be significantly visible. Possible redesigns for the function would be good especially regarding locking and fetching and comparing the expiration time 

`// Gc iterates through the Store looking for metrics that have been marked
// for expiry, and removing them if their expiration time has passed.
func (s *Store) Gc() error {
	glog.Info("Running Store.Expire()")
	s.Lock()
	defer s.Unlock()
	now := time.Now()
	for _, ml := range s.Metrics {
		for _, m := range ml {
			for _, lv := range m.LabelValues {
				if lv.Expiry <= 0 {
					continue
				}
				if now.Sub(lv.Value.TimeUTC()) > lv.Expiry {
					err := m.RemoveDatum(lv.Labels...)
					if err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
} `

**Comment by jaqx0r** [comment]
Yow, n^3! I knew it was bad but you're using a lot more metrics in the
store than me.

A rewrite of the store to be lock free or some alternative wont be before
the end of year unless someone can offer a pr.

**Comment by jaqx0r** [comment]
FYI `v3.0.0-rc41` is available which no longer uses fsnotify.

What would be really interesting is if you can attach the go tool pprof to a running mtail when the spike happens and collect the regular profile, the goroutine block profile, and the mutext profile, e.g. per https://jvns.ca/blog/2017/09/24/profiling-go-with-pprof/

Meanwhile I'm trying to reproduce your case with some benchmarks against metrics.Store but I'm not sure I've got much other than I can see that my plain old map is no good.

**Comment by jaqx0r** [comment]
OK the new benchmark seems to do a good job showing contention on the store between iterations over the store and garbage collections.  I think I have a simple fix as well.

**Comment by jaqx0r** [comment]
https://github.com/google/mtail/releases/tag/v3.0.0-rc43 has just been released and has what I think is a fix -- I would love it if you could try it out.

**Comment by rafaelpirolla** [comment]
Hi @jaqx0r, thank you very much for this job!

Since i've raised this one I ended up splitting mtail to parse some groups of file individually and the problem went away. There's still once a day issue in one hub and I'll sure try the new version there and let you know.

**Comment by rafaelpirolla** [comment]
It's fixed, jaqx0r... Awesome job!
