### ISSUE TITLE
http: mtail TLS/SSL support

### ISSUE THREAD

**Issue by yayajacky** [google/mtail#473]
Similar to node_exporter's TLS support (https://github.com/prometheus/node_exporter/issues/1286), it would be great to have TLS supported here using 
https://github.com/prometheus/exporter-toolkit

referenced before here:
https://github.com/google/mtail/pull/327#issuecomment-736065143

Alternatively, since most hosts I am working with have text file collection, having the option to emit prom text files directly without having an additional Cronjob performing curl to save it into the text file collection folder would be great.

Either options would reduce the number of components needed (nginx/or curl cronjob) to turn logs into metrics for prometheus ingestion.

Thanks!
Looking forward to v3 release

**Comment by uselessjargon** [comment]
TLS support would be a great addition. In the enterprise cloud world tls connections between distributed applications is becoming a hard requirement, even for something as basic as metrics.

**Comment by jaqx0r** [comment]
The linked bug and PR from node_exporter is massive.  I am very disinclined to make `mtail` more of a configurable websever than necessary.  That bug report does mention https://github.com/ghostunnel/ghostunnel or loopback mounting behind nginx, why are those not good options for you?

**Comment by uselessjargon** [comment]
I was trying to avoid having to install a ssl/tls proxy but it may have to do for my case. mtail is a great tool and we use it to extend the apache metrics we can't get with apache_exporter's server-status metrics. The apache exporter I use doesn't have native TLS either so using something like nginx or ghostunnel would solve the encrypted communications problem for all of my prometheus exporters and would be better than having to maintain my own forks of those projects.

Thanks for the response.

**Comment by jaqx0r** [comment]
I understand.  Fewer tools required to solve a task is great.   What I
don't want to do is add the complexity of certificate management to mtail
-- the existence of tools like ghostunnel make me think that it's not
trivial.  And with configuration management tools all over the place, the
cost I perceive of an additional tool that specialises in that doesn't seem
that great to me, while it returns significant value.

But if it's simple to add -- doesn't make the http server in mtail more
complex -- and simple to use -- maybe just command line flags to set the
certificates -- then I'd be happy to review a PR to add the support for it.

So I'm not promising that we'll add it, but if someone wants to work on the
feature and it doesn't terrify me, then I'll accept it.  (I can also
entertain the idea that someone else volunteers to be responsible for the
http server and any future maintenance required, in which case they just
make a blood oath rather than convince me to accept it.)
