### ISSUE TITLE
make has dependency to goyacc (an alias?)

### ISSUE THREAD

**Issue by thomas-b-jackson** [google/mtail#51]
I tried to build mtail for the first time this morning and got this error:

```
M00973008: /Users/x0ox/Dropbox/ActiveDev/go/src/github.com/google/mtail> make
# use prompt formatted as <hostname>: <path>/>
go generate -x ./vm
goyacc -v y.output -o parser.go -p mtail parser.y
vm/compiler.go:5: running "goyacc": exec: "goyacc": executable file not found in $PATH
```

I was able to workaround the error by:
1. creating the following alias:
alias goyacc="go tool yacc"
2. doing a go build in the vm directory
3. re-running make

**Comment by jaqx0r** [comment]
Sounds like a go version change issue.  What go version are you using?

**Comment by thomas-b-jackson** [comment]
>> go version
go version go1.7.1 darwin/amd64

**Comment by aurrelhebert** [comment]
Same here with 
go version go1.6.2 darwin/amd64

**Comment by emmanuel** [comment]
I worked around this with `go get golang.org/x/tools/cmd/goyacc` after `make install_deps`. 

In the `install_gen_deps` target in the Makefile, there is a download/update (but not install) of `goyacc` (`go get -u golang.org/x/tools/cmd/goyacc`), maybe the fix is merely to remove the `-u` flag from that line?

**Comment by jaqx0r** [comment]
Oh my, yes that would fix it. Can you send a PR?

On Thu., 15 Dec. 2016, 03:32 Emmanuel Gomez, <notifications@github.com>
wrote:

I worked around this with go get golang.org/x/tools/cmd/goyacc after make
install_deps.

In the install_gen_deps target in the Makefile, there is a download/update
(but not install) of goyacc (go get -u golang.org/x/tools/cmd/goyacc),
maybe the fix is merely to remove the -u flag from that line?

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/google/mtail/issues/51#issuecomment-267082220>, or mute
the thread

**Comment by Kak3n** [comment]
Hi I have this issue again when trying to run make or make install_deps mtail v3.0.0-rc13, `go version go1.10 linux/amd64`, OS `Debian GNU/Linux 9 (stretch)`,
