### ISSUE TITLE
Numerical expressions / numerical types issues

### ISSUE THREAD

**Issue by mjf** [google/mtail#68]
There _may_ be an issue with the numerical expressions or the `mtail`'s type system as such:

    $ cat progs/test.mtail
    counter t by le
    counter t_sum
    
    /^(?P<v>\d+(\.\d+)?)/ {
        $v < 0.5 {
                t["0.5"]++
        }
        $v < 1 {
                t["1"]++
        }
        t["inf"]++
        t_sum += $v
    }

    $ touch test.log
    $ mtail -progs progs -logs test.log

    $ curl -s localhost:3903/metrics
    # TYPE t counter
    # TYPE t_sum counter
    t_sum{prog="test.mtail",instance="test"} 0

    $ echo 0.1 >>test.log
    $ echo 1 >>test.log
    $ echo 1.765 >>test.log

    $ curl -s localhost:3903/metrics
    # TYPE t counter
    # TYPE t_sum counter
    t_sum{prog="test.mtail",instance="test"} 0

Q1: Am I missing something? (BTW: `mtail` itself produces neither warning nor error and simply does nothing in such a configuration.)

Q2: How do I cope with mixed integer and floting-point values in logs (such as the `delay=` and `delays=` values in `postfix` logs)?

**Sidenote:**

I would like to suggest `mtail` behaves similarly to `awk`. Please refer to for instance `gawk(1)` and look up the "Variable Typing And Conversion" paragraph to know more on this topic. The `awk`'s way **is** good-enough (and smart-enough) and would provide much more power to `mtail` users as well as _may_ be compatible with most existing `mtail` programs (not sure).

**Comment by jaqx0r** [comment]
Use --logtostderr to see the compiler logs on standard error.  Raise the
log level with --v=2.

This is a nice test case, thankyou!

The t counter is not being incremented so either the pattern is not
matching, or the comparison in $v < X is not working.  I suspect the latter
because I know I haven't got a unit test for that yet.

I will read the gawk manual, but my uninformed opinion is yes, the language
already copies awk so type conversion should too.

**Comment by mjf** [comment]
@jaqx0r 

I also think the `$v < X` expressions and similar are not working for some reason.

**Off-Topic:**

Does `$v == "literal"` work? It seems that string comparisons does not work at all. I would like to (for example):

    counter foo

    /(?P<w>\w+)/ {
        $w == "foo" {
            foo++
        }
    }

Does it make sense? ... But that does not seems to me to work either atm.

And there is also some problem with "namespaces" as I think. If you have a metric with same name as variable name for matches then something breaks:

    counter test
    
    /(?P<test>.*)/ {
        test++
    }

I have some intuitive idea why this is so. The problem is that the matched variables are denoted by the `$` sign and thus looking like from another "namespace" which is fairly counter-intuitive.

**Comment by jaqx0r** [comment]
String comparison does not work, until recently the only type supported was
integers.  Now there's floats if the compiler can figure it out, but that's
not working in your first example.
It should be easy to fix that and add string types.
The namespace problem is odd, the class of identifier object is distinct
between those two, so that should work fine. One is a capref and one is a
var. Clearly another poorly tested edge. Thanks again for the report!

**Comment by mjf** [comment]
@jaqx0r 

No problem. I would like to use `mtail` for many types of logs (and of course I'd also like to share the `mtail` programs with the community) but these few issues simply limit the use of it too much. 

I suppose that if some `counter c` contained `10` and I did `counter += 3.14` it results in `13.14` as I would expect (indeed, the "automagic" type conversion). Also add `int(float)` function to convert floating-point numbers to integers the similar way `awk` provides it. It may be very helpful in certain specific cases and as I hope simple to implement too. So that:

    counter i

    /^(\d+)$/ {
        # awk-ish trick
        i += 1.0 * $1
    }

will result in floating-point number (the cast done by either the `0.0 +` or `1.0 *` or any mixture of floating-point number and integer will result in floating-point number). And, on the other hand:

    counter f

    /^(\d+\.\d+)$/ {
        f += int($1)
    }

will never start to be a float in this simple case (because always converting `$1` to integer).

I you also added strings don't forget about the string to number and number to string conversions (as described in the `awk(1)`).

**Comment by jaqx0r** [comment]
Right now there is runtime conversion from string to int, but it is not
formally specified by the compiler and predates the type inference code
recently added.

Thanks for the feedback. Though I know i'd converge on these rules
eventually through my own use, having them written here helps immensely to
focus the next iteration of development.

**Comment by SuperQ** [comment]
@jaqx0r I'm also trying to figure out some type system issues.

I have a value that is logged as milliseconds, but I want to take that integer milliseconds and add that as float seconds to a counter.  I can't see how the `float()` or `i2f()` functions are supposed to work, there aren't any good examples.

**Comment by amper43** [comment]
@jaqx0r looks like that current language implementation not support all variables types
for follow statement:
```
X < Y {
  ACTION
}
```
X may be only $var from regexp
Y may be only const number
there isn't approach to compare any variable (defined as counter or gauge or from regexp) with other variable or with const. But it important in some cases. If you use mtail with prometheus and tailing logs with high incoming rate (access log with transactions for example) that comes high number of log lines between prometheus's scraping. In the same time it not guarantee that logs comes regular, with const interval and we can't use moving average in this case. If we could perform comparsion with any variables it will be real to calculate median or whatever else.

**Comment by jaqx0r** [comment]
Fixed:
1. Tested the original program in the first comment.
2. int() and float() type conversions are part of the language now.

Still outstanding from this report:

1. conditional expressions that do not look like $capref < constant, per @amper43's comment
i can't imagine why that restruction is in place but we need some more testing 

2. constant exprs that are strings (e.g. $v == "foo")
== str should work
```
counter foo

/(?P<w>\w+)/ {
    $w == "foo" {
        foo++
    }
}
```

3. namespace pollution for metric and capref names:
both test and $test should refer to different objects
```
counter test

/(?P<test>.*)/ {
    test++
}
```

4. metric type promotion
i should be float because of the 1.0
```
counter i

/^(\d+)$/ {
    # awk-ish trick
    i += 1.0 * $1
}
```

**Comment by jaqx0r** [comment]
(2) is done; we already have an end to end test "examples/logical.mtail" that proves this.

**Comment by jaqx0r** [comment]
(4) works; a commit not yet submitted will ensure this doesn't regress.

**Comment by jaqx0r** [comment]
(3) was a simple fix; now done awaiting push.

**Comment by jaqx0r** [comment]
I was misreading what (1) is about.  I think we should open a new bug about that one, but it rang a bell and #116 is already tracking that one.
