### ISSUE TITLE
Prometheus histogram examples should use inclusive upper bounds

### ISSUE THREAD

**Issue by mattbostock** [google/mtail#69]
The histogram examples that create Prometheus-compatible metrics (using an `le` label for distinguish buckets) should use an inclusive upper bound.

For example:

```
  $time_us < 5000 {
    apache_http_request_time_microseconds["5000"][$server_port][$handler][$request_method][$request_status][$request_protocol]++
  }
```

...should be:

```
  $time_us <= 5000 {
    apache_http_request_time_microseconds["5000"][$server_port][$handler][$request_method][$request_status][$request_protocol]++
  }
```

See: https://prometheus.io/docs/concepts/metric_types/#histogram

/cc @SuperQ

**Comment by SuperQ** [comment]
Ahh, yes, that is easily fixed.  I think there are also improvements we can make now that we support floats, we can convert the microseconds to a float seconds.

**Comment by rapaul** [comment]
I was looking at this example as a basis for work I'm doing. Translating up from microseconds to milliseconds seems like the right thing to do for web requests. So I was imagining the metric and label being better suited as milliseconds.

```
$time_us <= 5000 {
    apache_http_request_time_milliseconds["5"][$server_port][$handler][$request_method][$request_status][$request_protocol]++
  }
```

@SuperQ can you elaborate on what supporting floats does in this situation? Each of these metrics is a a counter where the millis is in the metric label (as a string rather than a float). Or do you mean it should be `apache_http_request_time_seconds` with with a label of `0.1`?

**Comment by SuperQ** [comment]
If you look at the [current example](https://github.com/google/mtail/blob/master/examples/apache_metrics.mtail#L39-L42) you can see that we translate `$time_us` into seconds, so 5000 becomes "0.005".  We recommend [seconds as the base unit](https://prometheus.io/docs/practices/naming/#base-units) for time so that it's easy to compare metrics from different sources.  Otherwise the PromQL user has to think about "is this seconds, or microseconds, or hours?".

Displaying the human unit is up to the display system, like Grafana, to show "5ms".
