### ISSUE TITLE
2 `subst()` calls within a single scope breaks compilation

### ISSUE THREAD

**Issue by EconomicTouristsArmLate** [google/mtail#810]
Having 2 `subst()` calls within a single scope breaks with the error message:

```
Redeclaration of capture group `0' previously declared at apache2.access.mtail:63:20-24
```

This example works fine:
```
gauge foo by asdf
gauge bar by asdf
/(?P<asdf>.+)/ {
  foo[subst(/\d/, "", $asdf)]++
  /.+/ {
    bar[subst(/\d/, "", $asdf)]++
  }
}
```

while this throws the `Redeclaration of capture group 0` error:
```
gauge foo by asdf
gauge bar by asdf
/(?P<asdf>.+)/ {
  foo[subst(/\d/, "", $asdf)]++
  bar[subst(/\d/, "", $asdf)]++
}
```

previous report: https://github.com/google/mtail/issues/693

**Comment by jaqx0r** [comment]
The problem is that the regular expression creates the numbered match
variables automatically, and the second regular expression then conflicts
in the same scope as the first.

There are two issues:

1) the numbered matches are not referenced so they should not matter

2) as the argument to subst the scope is even smaller and they should not
be leaking into the calling scope

Thanks for the report!
