### ISSUE TITLE
support for division in the vm

### ISSUE THREAD

**Issue by davidreuss** [google/mtail#9]
It would be useful if you could do divisions (and multiplication if that's missing too), so you can perform simple calculations yourself. As an example, keeping an average, with something like below

```
counter requests_total by vhost
gauge total_request_time by vhost
gauge avg_request_time by vhost

/(?P<vhost>\S+) (?P<latency>\d+)/ {
  requests_total[$vhost]++
  total_request_time[$vhost] += $latency
  avg_request_time[$vhost] = $total_request_time[$vhost] / $requests_total[$vhost]
}
```

Input would look like:

```
example.com 1231
foobar.com 123
```

And so on.

Not sure if it's intended to be able to do these calculations yourself in mtail itself, or it's best left up to exporters to calculate these types of metrics.

**Comment by jaqx0r** [comment]
It is easy to add mul/div to the language, but I did not before now because
computation on variables belongs in an aggregator, IMHO, like Prometheus,
Riemann, Heka, or Bosun. In those tools you will have more expressive power
to, say,  compute moving averages instead of this global avg.

But in #7 we mentioned that timer types would need to convert units of time
to the same SI prefix, so we do need these ops to do so.

So I will add them as they're useful for "correct" use of mtail, but you
will be free to use it as you see fit despite my recommendation :)

**Comment by jaqx0r** [comment]
One complication is that currently the VM deals entirely in ints, not floats, so the div will be an integer division in the first implementation.

**Comment by jaqx0r** [comment]
Another complicatoin is that using / as the quoting character for a regex literal, means it's difficult to lex a / as a division operator.  I'll submit my fix to add multiplication but div will take some thinking.

**Comment by davidreuss** [comment]
As mentioned in https://github.com/google/mtail/issues/9#issuecomment-126210256 you might be right about this is putting too much into mtail, and some of these calculations are better handled by other a little more heavyweight tools. I appreciate the effort though, and i still think it's useful for these more basic operations in mtail.
